export const mockDB = {
  buses: [
    {
      id: '1',
      name: 'Bus A',
      capacity: 50,
      wheelchairSlots: 2,
      currentWheelchairAvailability: 2,
      speed: 30,
    },
    {
      id: '2',
      name: 'Bus B',
      capacity: 50,
      wheelchairSlots: 2,
      currentWheelchairAvailability: 0,
      speed: 25,
    },
  ],
  trips: [
    {
      id: 'T1',
      busId: '1',
      routeId: 'R1',
      startTime: '08:00',
      stops: [
        {
          id: 'S1',
          name: 'Main Station',
          scheduledArrival: '08:00',
          location: { lat: 40.7128, lng: -74.006 },
          distanceFromPrev: 0,
        },
        {
          id: 'S2',
          name: 'Central Park',
          scheduledArrival: '08:15',
          location: { lat: 40.7829, lng: -73.9654 },
          distanceFromPrev: 6.3,
        },
      ],
      currentStopIndex: 0,
      wheelchairAvailable: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'T2',
      busId: '2',
      routeId: 'R1',
      startTime: '08:30',
      stops: [
        {
          id: 'S3',
          name: 'East Terminal',
          scheduledArrival: '08:30',
          location: { lat: 40.7336, lng: -73.9877 },
          distanceFromPrev: 0,
        },
        {
          id: 'S4',
          name: 'University Campus',
          scheduledArrival: '08:45',
          location: { lat: 40.7411, lng: -74.0049 },
          distanceFromPrev: 4.1,
        },
      ],
      currentStopIndex: 0,
      wheelchairAvailable: true,
      lastUpdated: new Date().toISOString(),
    },
  ],
  stops: [
    {
      id: 'S1',
      code: 'MAIN',
      name: 'Main Station',
      location: { lat: 40.7128, lng: -74.006 },
      amenities: ['wheelchair-accessible', 'ticket-office', 'restrooms'],
    },
    {
      id: 'S2',
      code: 'CPW',
      name: 'Central Park West',
      location: { lat: 40.7829, lng: -73.9654 },
      amenities: ['wheelchair-accessible', 'parking'],
    },
    {
      id: 'S3',
      code: 'MUSE',
      name: 'Museum District',
      location: { lat: 40.7794, lng: -73.9631 },
      amenities: ['wheelchair-accessible'],
    },
    {
      id: 'S4',
      code: 'FIND',
      name: 'Financial District',
      location: { lat: 40.7075, lng: -74.0113 },
      amenities: ['wheelchair-accessible', 'atm'],
    },
    {
      id: 'S5',
      code: 'MAIN',
      name: 'Main Station',
      location: { lat: 40.7128, lng: -74.006 },
      amenities: ['wheelchair-accessible', 'ticket-office', 'restrooms'],
    },
    {
      id: 'S6',
      code: 'EAST',
      name: 'East Terminal',
      location: { lat: 40.7336, lng: -73.9877 },
      amenities: ['wheelchair-accessible', 'parking', 'restrooms'],
    },
    {
      id: 'S7',
      code: 'UNIV',
      name: 'University Campus',
      location: { lat: 40.7411, lng: -74.0049 },
      amenities: ['wheelchair-accessible', 'bike-rack'],
    },
    {
      id: 'S8',
      code: 'LIB',
      name: 'Central Library',
      location: { lat: 40.7527, lng: -73.9812 },
      amenities: ['wheelchair-accessible', 'wifi'],
    },
  ],
};
